### ISSUE TITLE
Does running the installation script with Easy Apache Install the Current GPS Module?

### ISSUE THREAD

**Issue by rafaelmagic** [pagespeed/cpanel#35]
Hi,
I installed the script using the directions. Also ran Easy Apache but I am seeing the following header:
 X-Mod-Pagespeed: 1.3.25.4-2941
I believe the current Module is 1.9
So am I confused, install failed or is 1.3.25.4-2941 the most current compatible with WHM/Cpanel?

Thanks,
Rafael

**Comment by jeffkaufman** [comment]
1.3 is out of date and has security vulnerabilities; we should not be installing that for people!

The installation script seems to install one of:

    https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_i386.rpm
    https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_x86_64.rpm

Both of these are 1.9.32.4, not 1.3.25.4.

Had you ever downloaded/installed mod_pagespeed before?  It looks to me like the script might reuse an existing downloaded rpm if one was sitting there.

**Comment by rafaelmagic** [comment]
Fixed and Working.

I removed the following files:

/var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/Speed.pm
/var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/Speed.pm.tar.gz

Then went thru the install Process on the readme with EasyApache.

Module was installed by my Tech Support. 
Makes sense when you have lowcost managed hosting. They installed it wrong.

ReadMe should say, "Installs Current Version" and "Run Easy Apache to install Updates".

**Comment by rafaelmagic** [comment]
THANK YOU
