### ISSUE TITLE
RPM build errors:

### ISSUE THREAD

**Issue by hosamalzagh** [pagespeed/cpanel#40]
i tre this
https://github.com/Prajithp/cpanel/blob/master/README.md

1> yum install rpm-build cpio ea-apache24-mod_version
2> wget https://github.com/pagespeed/cpanel/raw/master/EA4/ea-apache24-mod_pagespeed-latest-stable.src.rpm
3> rpmbuild --rebuild ea-apache24-mod_pagespeed-latest-stable.src.rpm ---------------------------------------------------------------------------------- error
4> rpm -ivh /root/rpmbuild/RPMS/x86_64/ea-apache24-mod_pagespeed*.rpm
5> /etc/init.d/httpd restart

i have error in line 3 

moot@host [~]# rpmbuild --rebuild ea-apache24-mod_pagespeed-latest-stable.src.rp
Installing ea-apache24-mod_pagespeed-latest-stable.src.rpm
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.hxJaur
+ umask 022
+ cd /root/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ wget -q -N -O mod-pagespeed-stable.rpm https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_x86_64.rpm
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.B4myFO
+ umask 022
+ cd /root/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ rpm2cpio mod-pagespeed-stable.rpm
+ cpio -idmv
cpio: ./etc/cron.daily/mod-pagespeed not created: newer or same age version exists
./etc/cron.daily/mod-pagespeed
cpio: ./etc/httpd/conf.d/pagespeed.conf not created: newer or same age version exists
./etc/httpd/conf.d/pagespeed.conf
cpio: ./etc/httpd/conf.d/pagespeed_libraries.conf not created: newer or same age version exists
./etc/httpd/conf.d/pagespeed_libraries.conf
cpio: ./usr/bin/pagespeed_js_minify not created: newer or same age version exists
./usr/bin/pagespeed_js_minify
./usr/lib64/httpd/modules/mod_pagespeed.so
./usr/lib64/httpd/modules/mod_pagespeed_ap24.so
./var/cache/mod_pagespeed
./var/log/pagespeed
32590 blocks
+ mv usr/lib64/httpd/modules/mod_pagespeed.so usr/lib64/httpd/modules/mod_pagespeed_ap24.so .
+ /usr/bin/strip -g mod_pagespeed.so
+ /usr/bin/strip -g mod_pagespeed_ap24.so
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.1z0K5d
+ umask 022
+ cd /root/rpmbuild/BUILD
+ '[' /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64 '!=' / ']'
+ rm -rf /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64
++ dirname /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64
+ mkdir -p /root/rpmbuild/BUILDROOT
+ mkdir /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64
+ LANG=C
+ export LANG
+ unset DISPLAY
+ rm -rf /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64
+ mkdir -p '/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64%{_httpd_moddir}'
+ install -m755 mod_pagespeed.so '/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64%{_httpd_moddir}/'
+ install -m755 mod_pagespeed_ap24.so '/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64%{_httpd_moddir}/'
+ mkdir -p '/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64%{_httpd_modconfdir}'
+ install -m 644 /root/rpmbuild/SOURCES/456_pagespeed.conf '/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64%{_httpd_modconfdir}/'
+ /usr/lib/rpm/check-buildroot
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
+ /usr/lib/rpm/redhat/brp-compress
/usr/lib/rpm/redhat/brp-compress: line 8: cd: /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64: No such file or directory
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
+ /usr/lib/rpm/brp-python-bytecompile
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
Can't list /root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64
+ /usr/lib/rpm/redhat/brp-python-hardlink
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
+ /usr/lib/rpm/redhat/brp-java-repack-jars
find: `/root/rpmbuild/BUILDROOT/ea-apache24-mod_pagespeed-latest-stable.x86_64': No such file or directory
Processing files: ea-apache24-mod_pagespeed-latest-stable.x86_64
error: File must begin with "/": %{_httpd_moddir}/*.so
error: File must begin with "/": %{_httpd_modconfdir}/*.conf

RPM build errors:
File must begin with "/": %{_httpd_moddir}/*.so
File must begin with "/": %{_httpd_modconfdir}/*.conf

i used httpd 2.4.18 with EA4

**Comment by EdwardIII** [comment]
+1

**Comment by EdwardIII** [comment]
@hosamalzagh Have you tried the steps in the updated README here? #39

**Comment by EdwardIII** [comment]
@hosamalzagh This solution fixed --rebuild for me: https://github.com/pagespeed/cpanel/issues/38#issuecomment-166267521

@Prajithp Is it worth adding this to the README too?

**Comment by hosamalzagh** [comment]
thanks work

**Comment by Prajithp** [comment]
@EdwardIII Yes, I will add that too in README.
